### ISSUE TITLE
black unreadable chars in discord.py example

### ISSUE THREAD

**Issue by ITKewai** [discordextremelist/website#123] opened 2020-08-19 10:52 UTC
**Describe the Bug**

I've noticed that some parts of your website are not readable

**Steps to Reproduce**

[Examples / Discord.py](https://discordextremelist.xyz/en-US/docs#api-examples) 

unreadable `},` `: ` `{` `, `

**Screenshot**

![image](https://user-images.githubusercontent.com/11778454/90627367-b5564b00-e1d0-11ea-9156-7f7989524c45.png)

**Environment**

- OS: Windows 10
- Browser: Chrome
- Version: 84.0.4147.125 (Official Build) (64 bit) (cohort: Stable)

**Comment by advaith1** [comment] 2020-08-19 11:00
api reference page bug is a dupe of #121, but we'll keep this issue open for the discord.py example

**Comment by Cairo2k18** [comment] 2020-08-19 11:38
> api reference page bug is a dupe of #121, but we'll keep this issue open for the discord.py example

Examples, etc are related as it was to a bug with some variable being set and light theme.

**Closed** 2020-08-19 11:58 UTC
Labels: bug, high priority
