### ISSUE TITLE
Github Account doesn't Redirect to User

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/website#53] opened 2020-07-14 15:30 UTC
**Describe the Bug**

The Github account button on a user's profile just redirects to https://github.com not their github account
**Steps to Reproduce**

1. Go to [a profile on del](https://discordextremelist.xyz/users/443217277580738571) with a Github Account linked.
2. Click on the Github Button

**Expected Behavior**

It takes you to the account page
**Environment**

- OS: MacOS Catalina 10.15.5
- Browser: Chrome
- Version: 83.0.4103.116 (64-bit)

**Comment by Cairo2k18** [comment] 2020-07-15 01:43
Cannot reproduce on my profile

**Comment by advaith1** [comment] 2020-07-15 01:59
dupe of #50, @Cairo2k18 did u pull the fix?

**Comment by DuckMasterAl** [comment] 2020-07-15 02:08
> Cannot reproduce on my profile
@Cairo2k18 2 things:
1. When I try to reproduce it on your profile this happens 
<img width="1435" alt="Screen Shot 2020-07-14 at 10 06 34 PM" src="https://user-images.githubusercontent.com/43557963/87494987-52e0bc80-c61e-11ea-896f-65aff2a51bf5.png">
2. [Here's a video of it happening on my profile](https://youtu.be/3a1mkAzSGZI)

**Comment by DuckMasterAl** [comment] 2020-07-15 02:15
Ok, I tried this on other people's profiles with Github linked and it seems to work... this may only be affecting certain users.
It doesn't work on Ice or mine's profiles.

**Comment by advaith1** [comment] 2020-07-15 02:18
see #50, it'll bug if u don't have gitlab connected

**Comment by advaith1** [comment] 2020-07-15 02:27
fixed (in dev)

**Closed by advaith1** 2020-07-15 02:27 UTC
Labels: bug
